### ISSUE TITLE
Add Pagination for the Data Table 

### ISSUE THREAD

**Issue by pydevsg** [pydevsg/Bank-Filter-App#11]
Add Pagination in the website which will show 20 banks at a time.

**Comment by utpalendubarman** [comment]
I want to work in this issue

**Comment by pydevsg** [comment]
Hi, @utpalendubarman  please solve first issue which I have assigned to you, once it gets solved , I can assign you this issue if no else claims the issue till that time.

**Comment by pydevsg** [comment]
Great work @utpalendubarman :tada:
