### ISSUE TITLE
Add Banks of Hyderabad in the Data Table with  Search Box

### ISSUE THREAD

**Issue by pydevsg** [pydevsg/Bank-Filter-App#7]
API Used for fetching data - https://vast-shore-74260.herokuapp.com/banks?city=HYDERABAD

**Comment by ank1traj** [comment]
I would like to solve this issue.

**Comment by utpalendubarman** [comment]
I want to work in this issue

**Comment by ank1traj** [comment]
![hyderabad](https://user-images.githubusercontent.com/32160084/72222853-32f90f00-358f-11ea-9947-eedd24f1da9f.png)

**Comment by ank1traj** [comment]
![Annotation 2020-02-07 183626](https://user-images.githubusercontent.com/32160084/74032020-f9be8e00-49d8-11ea-8c31-316ad669836c.png)
