### ISSUE TITLE
Add banks of Pune in the Data Table with Search Box

### ISSUE THREAD

**Issue by pydevsg** [pydevsg/Bank-Filter-App#8]
API Used for fetching Data - https://vast-shore-74260.herokuapp.com/banks?city=PUNE

**Comment by ank1traj** [comment]
I would like to solve this issue.

**Comment by pydevsg** [comment]
Hi, @ank1traj  please solve first issue which I have assigned to you, once it gets solved , I can assign you this issue if no else claims the issue till that time.

**Comment by utpalendubarman** [comment]
I want to contribute

**Comment by agarwalBinay18** [comment]
i want to work on this issue

**Comment by pydevsg** [comment]
Hi @agarwalBinay18 , @ank1traj has worked on this and I am reviewing this task , I will soon add up some new issues.

**Comment by ank1traj** [comment]
![Annotation 2020-02-07 183039](https://user-images.githubusercontent.com/32160084/74032000-e90e1800-49d8-11ea-9c02-0c609eadf3ce.png)
