### ISSUE TITLE
Add banks of Indore in the Data Table with Search Box

### ISSUE THREAD

**Issue by pydevsg** [pydevsg/Bank-Filter-App#9]
API Used for fetching data - https://vast-shore-74260.herokuapp.com/banks?city=INDORE

**Comment by ank1traj** [comment]
I would like to solve this issue.

**Comment by pydevsg** [comment]
Hi, @ank1traj please solve first issue which I have assigned to you, once it gets solved , I can assign you these issue if no else claims the issue till that time.

**Comment by ank1traj** [comment]
@pydevsg Assign me this issue.

**Comment by pydevsg** [comment]
@ank1traj go ahead.

**Comment by ank1traj** [comment]
![Annotation 2020-02-07 183012](https://user-images.githubusercontent.com/32160084/74031977-d5fb4800-49d8-11ea-847f-46c867196f68.png)

**Comment by pydevsg** [comment]
The UI has completely changed @ank1traj . Please pull them once and then work accordingly.
You can see it live here - https://bank-filter-app.herokuapp.com
